pull_request_rules:
  - name: automatic update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=lint (ubuntu-latest, 3.10)
      - check-success=build_test_job (ubuntu-latest, 3.8, xorbits)
      - check-success=build_test_job (ubuntu-latest, 3.9, xorbits)
      - check-success=build_test_job (ubuntu-latest, 3.10, xorbits)
      - check-success=build_test_job (ubuntu-latest, 3.11, xorbits)
      - check-success=build_test_job (macos-latest, 3.8, xorbits)
      - check-success=build_test_job (macos-latest, 3.11, xorbits)
      - check-success=build_test_job (windows-latest, 3.8, xorbits)
      - check-success=build_test_job (windows-latest, 3.11, xorbits)
      - check-success=build_test_job (ubuntu-latest, _mars/dataframe, 3.9)
      - check-success=build_test_job (ubuntu-latest, _mars/tensor, 3.9)
      - check-success=build_test_job (ubuntu-latest, _mars/learn, 3.9)
      - check-success=build_test_job (ubuntu-latest, mars-core, 3.9)
      - check-success=build_test_job (ubuntu-latest, compatibility, 3.9)
      - check-success=codecov/project
      - check-success=docs/readthedocs.org:xorbits
      - base=main
    actions:
      merge:
        method: squash
