version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: doc/requirements-doc.txt
    - method: pip
      path: python

submodules:
  recursive: true
