version: 2
formats: []

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py


build:
  tools:
    python: "3.9"

python:
  install:
    - requirements: doc/requirements-doc.txt
    - method: pip
      path: python
