version: 2
formats: []

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

python:
  version: "3"
  install:
    - requirements: doc/requirements-doc.txt
    - method: pip
      path: python
