version: "2.2"

services:
  mysql:
    image: mysql:5.7.29
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      common-network:

  slurmdbd:
    image: daskdev/dask-jobqueue:slurm
    build: .
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      common-network:

  slurmctld:
    image: daskdev/dask-jobqueue:slurm
    build: .
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    environment:
      - CI_SHARED_SPACE=/shared_space
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../..:/xorbits
      - shared_space:/shared_space
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      common-network:
        ipv4_address: 10.1.1.10
    cap_add:
      - NET_ADMIN

  c1:
    image: daskdev/dask-jobqueue:slurm
    build: .
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../..:/xorbits
      - shared_space:/shared_space
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      common-network:
        ipv4_address: 10.1.1.11
    cap_add:
      - NET_ADMIN

  c2:
    image: daskdev/dask-jobqueue:slurm
    build: .
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../..:/xorbits
      - shared_space:/shared_space
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      common-network:
        ipv4_address: 10.1.1.12
    cap_add:
      - NET_ADMIN

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  shared_space:

networks:
  common-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
