name: Assign
on:
  issue_comment:
    types: created

permissions:
  contents: read

jobs:
  issue_assign:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
    - if: github.event.comment.body == 'take'
      run: |
        echo "Assigning issue ${{ github.event.issue.number }} to ${{ github.event.comment.user.login }}"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
